    version: '2'
    services:
        db:
            image: "postgres"
            ports:
                - "5432:5432"
            environment:
                POSTGRES_USER: docker
                POSTGRES_PASSWORD: docker
            volumes:
                - database:/var/lib/postgresql/data

    volumes:
        database:
